In [24]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [25]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("data/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rainfall 3hr,Snowfall 3hr,Date
0,0,Tiksi,RU,71.69,128.87,38.07,90,100,5.79,light rain,0.0,0.0,2020-06-14 21:18:40
1,1,Mataura,NZ,-46.19,168.86,39.00,83,97,3.00,overcast clouds,0.0,0.0,2020-06-14 21:17:33
2,2,Ushuaia,AR,-54.80,-68.30,33.80,74,40,3.36,scattered clouds,0.0,0.0,2020-06-14 21:15:44
3,3,Lagoa,PT,39.05,-27.98,62.37,73,11,10.02,few clouds,0.0,0.0,2020-06-14 21:20:40
4,4,Thompson,CA,55.74,-97.86,78.80,41,75,10.29,broken clouds,0.0,0.0,2020-06-14 21:20:38

In [26]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [27]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
raining  = input("Do you want it to be raining? (yes/no) ")
snowing  = input("Do you want it to be snowing? (yes/no) ")

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [28]:
if raining == "yes" :
    raining = True
else:
    raining = False
if snowing == "yes" :
    snowing = True
else:
    snowing = False

In [29]:
if raining == "yes" and snowing == "yes":
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["Rainfall 3hr"] > 0) &\
                                          (city_data_df["Snowfall 3hr"] > 0)]
elif raining == "yes" and snowing == "no":
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["Rainfall 3hr"] > 0) &\
                                          (city_data_df["Snowfall 3hr"] == 0)]                                           
elif raining == "no" and snowing == "no":
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["Rainfall 3hr"] == 0) &\
                                          (city_data_df["Snowfall 3hr"] == 0)]
elif raining == "no" and snowing == "yes":   
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["Rainfall 3hr"] == 0) &\
                                          (city_data_df["Snowfall 3hr"] > 0)]

In [30]:
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rainfall 3hr,Snowfall 3hr,Date
4,4,Thompson,CA,55.74,-97.86,78.80,41,75,10.29,broken clouds,0.0,0.0,2020-06-14 21:20:38
17,17,Calabozo,VE,8.92,-67.43,86.13,70,61,5.75,broken clouds,0.0,0.0,2020-06-14 21:19:56
18,18,Novo Aripuana,BR,-5.12,-60.38,85.30,67,92,1.41,overcast clouds,0.0,0.0,2020-06-14 21:26:44
21,21,Puerto Ayora,EC,-0.74,-90.35,77.00,73,40,13.87,scattered clouds,0.0,0.0,2020-06-14 21:18:18
22,22,Avarua,CK,-21.21,-159.78,75.20,50,75,8.05,broken clouds,0.0,0.0,2020-06-14 21:20:04
26,26,Mandera,KE,3.94,41.87,81.23,54,48,16.98,scattered clouds,0.0,0.0,2020-06-14 21:26:46
28,28,Padang,ID,-0.95,100.35,79.41,78,44,3.22,light rain,0.0,0.0,2020-06-14 21:20:19
29,29,Atuona,PF,-9.80,-139.03,80.44,73,24,14.58,few clouds,0.0,0.0,2020-06-14 21:19:00
30,30,Hilo,US,19.73,-155.09,77.00,69,75,3.36,light rain,0.0,0.0,2020-06-14 21:16:15
33,33,Dalbandin,PK,28.89,64.41,84.65,13,0,3.33,clear sky,0.0,0.0,2020-06-14 21:26:47

In [31]:
hotel_df = preferred_cities_df[["City","Country","Max Temp","Current Description","Lat","Lng"]]
hotel_df["Hotel Name"] = ""
hotel_df.head()

C:\Users\laksh\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Thompson,CA,78.80,broken clouds,55.74,-97.86,
17,Calabozo,VE,86.13,broken clouds,8.92,-67.43,
18,Novo Aripuana,BR,85.30,overcast clouds,-5.12,-60.38,
21,Puerto Ayora,EC,77.00,scattered clouds,-0.74,-90.35,
22,Avarua,CK,75.20,broken clouds,-21.21,-159.78,

In [32]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

C:\Users\laksh\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [33]:
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Thompson,CA,78.80,broken clouds,55.74,-97.86,Burntwood Hotel
17,Calabozo,VE,86.13,broken clouds,8.92,-67.43,Hotel Giardini
18,Novo Aripuana,BR,85.30,overcast clouds,-5.12,-60.38,Hotel Ypê
21,Puerto Ayora,EC,77.00,scattered clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
22,Avarua,CK,75.20,broken clouds,-21.21,-159.78,Paradise Inn

In [34]:
# Create the output file (CSV).
output_data_file = "data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [35]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [36]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
#max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
#             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))