In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("data/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rainfall 3hr,Snowfall 3hr,Date
0,0,Cidreira,BR,-30.18,-50.21,51.73,72,4,3.53,clear sky,0.0,0.0,2020-06-14 22:48:42
1,1,Ishigaki,JP,24.34,124.16,82.40,100,40,5.82,scattered clouds,0.0,0.0,2020-06-14 22:50:43
2,2,Busselton,AU,-33.65,115.33,55.00,71,88,9.66,overcast clouds,0.0,0.0,2020-06-14 22:50:43
3,3,Kupang,ID,-10.17,123.58,73.40,94,20,3.36,few clouds,0.0,0.0,2020-06-14 22:50:44
4,4,Airai,TL,-8.93,125.41,61.00,97,8,4.50,clear sky,0.0,0.0,2020-06-14 22:50:44

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [8]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
raining  = input("Do you want it to be raining? (yes/no) ")
snowing  = input("Do you want it to be snowing? (yes/no) ")

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [9]:
if raining == "yes" and snowing == "yes":
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["Rainfall 3hr"] > 0) &\
                                          (city_data_df["Snowfall 3hr"] > 0)]
elif raining == "yes" and snowing == "no":
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["Rainfall 3hr"] > 0) &\
                                          (city_data_df["Snowfall 3hr"] == 0)]                                           
elif raining == "no" and snowing == "no":
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["Rainfall 3hr"] == 0) &\
                                          (city_data_df["Snowfall 3hr"] == 0)]
elif raining == "no" and snowing == "yes":   
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["Rainfall 3hr"] == 0) &\
                                          (city_data_df["Snowfall 3hr"] > 0)]

In [10]:
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rainfall 3hr,Snowfall 3hr,Date
1,1,Ishigaki,JP,24.34,124.16,82.40,100,40,5.82,scattered clouds,0.0,0.0,2020-06-14 22:50:43
5,5,Diapaga,BF,12.07,1.79,82.15,58,86,14.07,moderate rain,0.0,0.0,2020-06-14 22:50:44
6,6,Laizhou,CN,37.18,119.93,75.24,32,98,3.94,overcast clouds,0.0,0.0,2020-06-14 22:50:44
7,7,Vaini,TO,-21.20,-175.20,75.20,69,40,11.41,scattered clouds,0.0,0.0,2020-06-14 22:50:45
8,8,Rikitea,PF,-23.12,-134.97,76.17,84,41,14.58,scattered clouds,0.0,0.0,2020-06-14 22:49:58
12,12,Meulaboh,ID,4.14,96.13,77.05,89,100,4.32,overcast clouds,0.0,0.0,2020-06-14 22:50:46
18,18,Saint Anthony,US,45.02,-93.22,77.00,33,1,25.28,clear sky,0.0,0.0,2020-06-14 22:50:47
24,24,Basavana Bagevadi,IN,16.58,75.97,76.30,78,100,17.02,overcast clouds,0.0,0.0,2020-06-14 22:50:49
26,26,Victoria,HK,22.29,114.16,82.00,83,91,5.99,light rain,0.0,0.0,2020-06-14 22:50:49
27,27,Oranjestad,AW,12.52,-70.03,84.20,74,20,27.51,few clouds,0.0,0.0,2020-06-14 22:46:35

In [11]:
hotel_df = preferred_cities_df[["City","Country","Max Temp","Current Description","Lat","Lng"]]
hotel_df["Hotel Name"] = ""
hotel_df.head()

C:\Users\laksh\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       City Country  Max Temp Current Description    Lat     Lng Hotel Name
1  Ishigaki      JP     82.40    scattered clouds  24.34  124.16
5   Diapaga      BF     82.15       moderate rain  12.07    1.79
6   Laizhou      CN     75.24     overcast clouds  37.18  119.93
7     Vaini      TO     75.20    scattered clouds -21.20 -175.20
8   Rikitea      PF     76.17    scattered clouds -23.12 -134.97

In [12]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

C:\Users\laksh\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [13]:
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Ishigaki,JP,82.40,scattered clouds,24.34,124.16,Hotel Peace Land Ishigakijima
5,Diapaga,BF,82.15,moderate rain,12.07,1.79,
6,Laizhou,CN,75.24,overcast clouds,37.18,119.93,Baidu International Hotel
7,Vaini,TO,75.20,scattered clouds,-21.20,-175.20,Keleti Beach Resort
8,Rikitea,PF,76.17,scattered clouds,-23.12,-134.97,Pension Maro'i

In [14]:
# Create the output file (CSV).
output_data_file = "data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [16]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [17]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
#max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
#             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))