In [10]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [11]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,rainfall 1hr,snowfall 1hr,Date
0,0,Kununurra,AU,-15.77,128.73,62.60,30,0,2.24,clear sky,0.0,0.0,2020-06-14 19:27:13
1,1,Oistins,BB,13.07,-59.53,87.80,62,20,20.80,few clouds,0.0,0.0,2020-06-14 19:23:12
2,2,Eureka,US,40.80,-124.16,68.00,50,93,4.00,overcast clouds,0.0,0.0,2020-06-14 19:24:55
3,3,Lodja,CD,-3.48,23.43,74.32,54,0,1.57,clear sky,0.0,0.0,2020-06-14 19:27:13
4,4,Mayo,US,38.89,-76.51,75.99,56,1,8.05,clear sky,0.0,0.0,2020-06-14 19:27:14

In [12]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [13]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
raining  = input("Do you want it to be raining? (yes/no) ")
snowing  = input("Do you want it to be snowing? (yes/no) ")

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [ ]:
if raining == "yes" :
    raining = True
else:
    raining = False
if snowing == "yes" :
    snowing = True
else
    snowing = False

In [14]:
if raining == "yes" and snowing == "yes":
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["rainfall 1hr"] > 0) &\
                                          (city_data_df["snowfall 1hr"] > 0)]
elif raining == "yes" and snowing == "no":
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["rainfall 1hr"] > 0) &\
                                          (city_data_df["snowfall 1hr"] == 0)]                                           
elif raining == "no" and snowing == "no":
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["rainfall 1hr"] == 0) &\
                                          (city_data_df["snowfall 1hr"] == 0)]
elif raining == "no" and snowing == "yes":   
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) &\
                                        (city_data_df["rainfall 1hr"] == 0) &\
                                          (city_data_df["snowfall 1hr"] > 0)]

In [15]:
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,rainfall 1hr,snowfall 1hr,Date
1,1,Oistins,BB,13.07,-59.53,87.80,62,20,20.80,few clouds,0.0,0.0,2020-06-14 19:23:12
4,4,Mayo,US,38.89,-76.51,75.99,56,1,8.05,clear sky,0.0,0.0,2020-06-14 19:27:14
6,6,Kahului,US,20.89,-156.47,82.40,54,20,21.92,few clouds,0.0,0.0,2020-06-14 19:27:07
8,8,Fort-Shevchenko,KZ,44.51,50.26,89.11,28,0,26.57,clear sky,0.0,0.0,2020-06-14 19:27:15
36,36,Rikitea,PF,-23.12,-134.97,75.76,81,0,18.16,clear sky,0.0,0.0,2020-06-14 19:27:21
38,38,Gat,IL,31.61,34.76,75.99,75,0,8.32,clear sky,0.0,0.0,2020-06-14 19:27:21
39,39,Porbandar,IN,21.64,69.61,86.22,83,100,9.55,overcast clouds,0.0,0.0,2020-06-14 19:27:18
41,41,Sao Filipe,CV,14.90,-24.50,77.43,78,0,10.54,clear sky,0.0,0.0,2020-06-14 19:27:10
49,49,Pitimbu,BR,-7.47,-34.81,82.40,78,75,13.87,broken clouds,0.0,0.0,2020-06-14 19:23:32
51,51,Lorengau,PG,-2.02,147.27,82.54,75,100,7.96,overcast clouds,0.0,0.0,2020-06-14 19:27:25

In [22]:
hotel_df = preferred_cities_df[["City","Country","Max Temp","Current Description","Lat","Lng"]]
hotel_df["Hotel Name"] = ""
hotel_df.head()

C:\Users\laksh\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Oistins,BB,87.80,few clouds,13.07,-59.53,
4,Mayo,US,75.99,clear sky,38.89,-76.51,
6,Kahului,US,82.40,few clouds,20.89,-156.47,
8,Fort-Shevchenko,KZ,89.11,clear sky,44.51,50.26,
36,Rikitea,PF,75.76,clear sky,-23.12,-134.97,

In [23]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

C:\Users\laksh\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [31]:
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Oistins,BB,87.80,few clouds,13.07,-59.53,Butterfly Beach Hotel
4,Mayo,US,75.99,clear sky,38.89,-76.51,Resorts Resource Group International
6,Kahului,US,82.40,few clouds,20.89,-156.47,Maui Seaside Hotel
8,Fort-Shevchenko,KZ,89.11,clear sky,44.51,50.26,Oasis hotel Bautino
36,Rikitea,PF,75.76,clear sky,-23.12,-134.97,Pension Maro'i

In [32]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy_vacation_map.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [28]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [29]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
#max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
#             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))